sails:
    build: .
    ports:
      - "8001:80"
    links:
      - postgres
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    command: node app
  
  postgres:
      image: postgres:latest
      ports:
        - "8002:5432"